version: '3'
services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 25565:25565
    volumes:
      - ./src:/src
#    environment:
#      - MINECRAFT_VERSION=1.14.4